create table if not exists public.telegram_signal_threads (
  id bigint generated by default as identity primary key,
  token_id uuid not null references public.tokens(id) on delete cascade,
  chat_id text not null,
  root_message_id bigint not null,
  started_at timestamptz not null default now(),
  reference_price_usd numeric,
  peak_price_usd numeric,
  peak_return_pct numeric not null default 0,
  last_milestone_pct numeric not null default 0,
  last_update_at timestamptz,
  active boolean not null default true,
  image_url text,
  metadata jsonb not null default '{}'::jsonb,
  unique (token_id, chat_id)
);

create index if not exists idx_telegram_signal_threads_active_started
  on public.telegram_signal_threads (active, started_at desc);

alter table public.telegram_signal_threads enable row level security;
revoke all on table public.telegram_signal_threads from anon, authenticated;
grant select, insert, update, delete on table public.telegram_signal_threads to service_role;
grant usage, select on all sequences in schema public to service_role;
